title: 👢 Strap
description: A script to bootstrap a minimal macOS development system with the minimal set of settings and software every macOS developer will want.
url: https://strap.mikemcquaid.com

author:
  name: Mike McQuaid
  email: mike@mikemcquaid.com
  uri: https://mikemcquaid.com
  twitter: MikeMcQuaid

twitter:
  username: MikeMcQuaid
  card: summary

social:
  name: Mike McQuaid
  links:
    - https://github.com/MikeMcQuaid
    - https://mastodon.social/@mikemcquaid
    - https://www.linkedin.com/in/mkmcqd
    - https://twitter.com/MikeMcQuaid

permalink: "/:title/"

exclude:
  - bin
  - CNAME
  - Gemfile*
  - LICENSE.txt
  - Rakefile,
  - README.md
  - vendor

plugins:
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-titles-from-headings

github:
  repository_nwo: MikeMcQuaid/strap
